name: path-filter
on:
  push:
    paths:
    - '.github/workflows/part1/*'
    - '!.github/workflows/part1/push.yaml'

jobs:
  branch-filter:
    runs-on: ubuntu-lateat
    steps:
    - name: echo
      run: echo hello