name: if-condition2
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: exit1
      run: exit1
    - name: echo
      run: echo hello

  job2:
    needs: [job1]
    runs-on: ubuntu-latest
    #강제실행
    if: always()
    steps:
      - name: echo
        run: echo hello
